vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /src/img/dogs
            upload_destination: '%kernel.project_dir%/public/src/img/dogs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
